FileDevice Yes
ServerBin @SANDBOX@/libexec/cups
DataDir @SANDBOX@/share/cups
DocumentRoot @SANDBOX@/share/doc/cups
RequestRoot @SANDBOX@/var/spool/cups
CacheDir @SANDBOX@/var/cache/cups
StateDir @SANDBOX@/var/run
TempDir @SANDBOX@/var/spool/cups/tmp
AccessLog @SANDBOX@/var/log/cups/access_log
ErrorLog @SANDBOX@/var/log/cups/error_log
PageLog @SANDBOX@/var/log/cups/page_log
User @USER@
Group @GROUP@
