LogLevel debug2
Listen localhost:16632
ServerRoot @SANDBOX@/etc/cups
ServerBin @SANDBOX@/libexec/cups
DataDir @SANDBOX@/share/cups
DocumentRoot @SANDBOX@/share/doc/cups
RequestRoot @SANDBOX@/var/spool/cups
CacheDir @SANDBOX@/var/cache/cups
StateDir @SANDBOX@/var/run
TempDir @SANDBOX@/var/spool/cups/tmp
AccessLog @SANDBOX@/var/log/cups/access_log
ErrorLog @SANDBOX@/var/log/cups/error_log
PageLog @SANDBOX@/var/log/cups/page_log
FileDevice Yes
PreserveJobFiles Yes
PreserveJobHistory Yes
MaxLogSize 0
DefaultAuthType None
WebInterface No
<Location />
  Order allow,deny
  Allow localhost
</Location>
<Location /admin>
  Order allow,deny
  Allow localhost
</Location>
<Policy default>
  <Limit All>
    Order deny,allow
  </Limit>
</Policy>
Sandboxing Off
